# Generated by Django 4.2.7 on 2023-12-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('jobSeeker', 'Job Seeker'), ('employer', 'Employer')], max_length=20, null=True),
        ),
    ]
