# Generated by Django 4.2.7 on 2023-12-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='company_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logo/'),
        ),
    ]
