# Generated by Django 4.2.7 on 2023-12-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_employer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
