# Generated by Django 4.2.7 on 2023-12-09 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
