# Generated by Django 4.2.7 on 2023-12-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_userprofile_email_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='educational_attainment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
