# Generated by Django 4.2.7 on 2023-12-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_jobposting_application_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('freelancer', 'Freelancer'), ('part_time', 'Part Time'), ('intern', 'Intern')], default='full_time', max_length=20),
        ),
    ]
