# Generated by Django 4.2.7 on 2023-12-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_userprofile_educational_attainment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='educational_attainment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
