# Generated by Django 4.2.7 on 2023-12-13 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0010_usercv'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduateTracer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_department', models.CharField(choices=[('', 'Choose'), ('College of Information and Communication Technology (CICT)', 'College of Information and Communication Technology (CICT)'), ('College of Business Administration (CBA)', 'College of Business Administration (CBA)'), ('College of Architecture and Fine Arts (CAFA)', 'College of Architecture and Fine Arts (CAFA)'), ('College of Arts and Letters (CAL)', 'College of Arts and Letters (CAL)'), ('College of Criminal Justice Education (CCJE)', 'College of Criminal Justice Education (CCJE)'), ('College of Social Science and Philosophy (CSSP)', 'College of Social Science and Philosophy (CSSP)'), ('College of Home Economics (CHE)', 'College of Home Economics (CHE)'), ('College of Industrial Technology (CIT)', 'College of Industrial Technology (CIT)'), ('College of Nursing (CON)', 'College of Nursing (CON)'), ('College of Engineering (COE)', 'College of Engineering (COE)'), ('College of Education (COED)', 'College of Education (COED)'), ('College of Sports, Exercise and Recreation', 'College of Sports, Exercise and Recreation'), ('College of Science (CS)', 'College of Science (CS)')], default='', max_length=255)),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
                ('year_graduated', models.CharField(choices=[('', 'Select Year'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')], default='', max_length=4)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Separated', 'Separated'), ('Widowed', 'Widowed'), ('Other', 'Other')], default='Other', max_length=10)),
                ('age', models.CharField(choices=[('', 'Select Age'), ('Below 20', 'Below 20'), ('20-25', '20-25'), ('26-30', '26-30'), ('31-35', '31-35'), ('36-40', '36-40'), ('Above 40', 'Above 40'), ('Other', 'Other')], default='', max_length=10)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('education_level', models.CharField(choices=[('', 'Select'), ('Certificate in Two Year Course', 'Certificate in Two Year Course'), ('College Graduate', 'College Graduate'), ('with Units in Masters Degree', 'with Units in Masters Degree'), ('Masters Degree Holder', 'Masters Degree Holder'), ('with Doctoral Degree', 'with Doctoral Degree'), ('Doctoral Degree Holder', 'Doctoral Degree Holder')], default='', max_length=50)),
                ('scholarship', models.CharField(choices=[('', 'Select'), ('Yes, I am a recipient of a GOVERTNMENT scholarship program', 'Yes, I am a recipient of a GOVERTNMENT scholarship program'), ('Yes, I am recipient of a PRIVATE scholarship program', 'Yes, I am recipient of a PRIVATE scholarship program'), ('No, I am not a recipient of ANY scholarship program', 'No, I am not a recipient of ANY scholarship program')], default='', max_length=100)),
                ('presently_employed', models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('Never', 'Never')], default='', max_length=10)),
                ('unemployment_reason', models.TextField(blank=True, max_length=200, null=True)),
                ('employment_status', models.CharField(choices=[('', 'Select'), ('Regular/Permanent', 'Regular/Permanent'), ('Contractual', 'Contractual'), ('Temporary', 'Temporary'), ('Self-Employed', 'Self-Employed')], default='', max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('line_of_business', models.CharField(choices=[('', 'Select'), ('Agriculture', 'Agriculture'), ('Hunting and Forestry', 'Hunting and Forestry'), ('Fishing', 'Fishing'), ('Mining', 'Mining'), ('Construction', 'Construction'), ('Manufacturing', 'Manufacturing'), ('Transportation', 'Transportation'), ('Communication', 'Communication'), ('Finance', 'Finance'), ('Real Estate', 'Real Estate'), ('Education', 'Education'), ('Healthcare', 'Healthcare'), ('Technology', 'Technology'), ('Retail', 'Retail'), ('Hospitality', 'Hospitality'), ('Arts and Entertainment', 'Arts and Entertainment'), ('Other', 'Other')], default='', max_length=200)),
                ('work_place', models.CharField(choices=[('', 'Select'), ('Local', 'Local'), ('Abroad', 'Abroad')], default='', max_length=10)),
                ('firstjob_after_college', models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No')], default='', max_length=3)),
                ('reasons_for_staying', models.TextField(blank=True, max_length=200, null=True)),
                ('firstjob_related', models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No')], default='', max_length=3)),
                ('reason_for_accepting', models.TextField(blank=True, max_length=200, null=True)),
                ('reason_for_changing', models.TextField(blank=True, max_length=200, null=True)),
                ('firstjob_duration', models.CharField(choices=[('', 'Select'), ('less than a month', 'Less than a month'), ('1 to 6 months', '1 to 6 months'), ('7 to 11 months', '7 to 11 months'), ('1 year to less than 2 years', '1 year to less than 2 years'), ('2 years to less than 3 years', '2 years to less than 3 years'), ('3 years to less than 4 years', '3 years to less than 4 years'), ('Other', 'Other')], default='', max_length=30)),
                ('find_your_firstjob', models.TextField(blank=True, max_length=200, null=True)),
                ('firstjob_land_duration', models.CharField(choices=[('', 'Select'), ('less than a month', 'Less than a month'), ('1 to 6 months', '1 to 6 months'), ('7 to 11 months', '7 to 11 months'), ('1 year to less than 2 years', '1 year to less than 2 years'), ('2 years to less than 3 years', '2 years to less than 3 years'), ('3 years to less than 4 years', '3 years to less than 4 years'), ('Other', 'Other')], default='', max_length=30)),
                ('where_you_find_firstjob', models.TextField(blank=True, max_length=200, null=True)),
                ('monthly_earning', models.CharField(choices=[('', 'Select'), ('Below ₱5,000,00', 'Below ₱5,000,00'), ('₱5,000,00 to less than ₱10,000,00', '₱5,000,00 to less than ₱10,000,00'), ('₱10,000,00 to ₱15,000,00', '₱10,000,00 to ₱15,000,00'), ('₱15,000,00 to ₱20,000,00', '₱15,000,00 to ₱20,000,00'), ('₱20,000,00 to ₱25,000,00', '₱20,000,00 to ₱25,000,00'), ('₱25,000,00 to ₱30,000,00', '₱25,000,00 to ₱30,000,00'), ('Other', 'Other')], default='', max_length=200)),
                ('curriculum_relevance_firstjob', models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No')], default='', max_length=5)),
                ('competencies_usefull_firstjob', models.TextField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
