# Generated by Django 4.2.7 on 2023-12-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_graduatetracer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='skill_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
